# Generated by Django 5.0.4 on 2024-06-29 03:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
    ]
